### ISSUE TITLE
Use the SRC-2 Standard for Inline Documentation

### ISSUE THREAD

**Issue by partylikeits1983** [burralabs/ruscet-contracts#11]
# Add natspec type comments for main public functions

Severity: Informational

Type: Documentation

### Recommendation

Consider adding natspec type comments to improve the clarity of the codebase and to make it easier for other projects to integrate with the Ruscet Contracts. The lack of documentation can make it more difficult to quickly understand the functionality of certain functions.

**Comment by theausicist** [comment]
acknowledged

**Comment by partylikeits1983** [comment]
After suggestions from the Fuel team, instead of using Natspec formatting it is recommended to use the SRC-2 standard for inline documentation: https://docs.fuel.network/docs/sway-standards/src-2-inline-documentation/
