### ISSUE TITLE
Contracts Uninitialized on deploy

### ISSUE THREAD

**Issue by partylikeits1983** [burralabs/ruscet-contracts#12]
# Contracts Uninitialized on deploy

Severity: Low

Type: Contract Initialization

All `initialize()` functions present in the codebase allow any caller to initialize the contract.

### Recommendation:

To prevent unwanted initialization, or the possibility of the non-initialization of a contract, consider setting the address of the initializor in configurables.

Configurable constants:
https://docs.fuel.network/docs/sway/basics/constants/#configurable-constants

**Comment by theausicist** [comment]
this is likely a non-issue because even if the initialize() method is frontrun, a subsequent call (ours) will revert because said contract was initialized. Easy fix is to redeploy the contract
