### ISSUE TITLE
Use Latest Versions of fuels-ts, forc, and fuel-core for production deployment

### ISSUE THREAD

**Issue by partylikeits1983** [burralabs/ruscet-contracts#23]
# Use Latest Versions of fuels-ts, forc, and fuel-core for production deployment

Severity: Informational

Type: Dependencies

Ensure that fuels-ts, forc, and fuel-core are updated to their latest versions at the time of deployment. Currently the most up to date versions are: fuels-ts `v0.94.6`, forc `v0.64.0`, and fuel-core `v0.36.0`

**Comment by theausicist** [comment]
bumped
