### ISSUE TITLE
Unused variables in function input `get_funding_fee()`

### ISSUE THREAD

**Issue by partylikeits1983** [burralabs/ruscet-contracts#7]
# Unused variables in function input `get_funding_fee()`

Severity: Informational

Type: Optimization

The function get_funding_fee() contains input parameters that are not used in the function body. Specifically, the parameters `account`, `index_asset`, and `is_long` are passed into the function but never utilized. This results in unnecessary complexity and could potentially lead to slight inefficiencies.

Impact:
* Gas Optimization: Although the impact is minimal, reducing unnecessary input parameters can slightly improve gas usage.
* Code Readability: Removing unused parameters improves code clarity and maintainability.

`get_funding_rate()`: https://github.com/burralabs/ruscet-contracts/blob/93c58b12d72429d1a680429bcbf72c4246a70502/contracts/core/vault-utils/src/main.sw#L262

```rust
#[storage(read)]
fn get_funding_fee(
    account: Account,
    collateral_asset: AssetId,
    index_asset: AssetId,
    is_long: bool,
    size: u256,
    entry_funding_rate: u256,
) -> u256 {
    _get_funding_fee(
        collateral_asset,
        size,
        entry_funding_rate
    )
}
```

### Recommendation

Remove the unused input parameters `account`, `index_asset`, and `is_long` from the `get_funding_fee()` function signature. Update all instances where this function is called to reflect the updated parameter list. This will help reduce gas costs and improve code readability.

**Comment by theausicist** [comment]
similar to #10, this breaks some compiler inlining optimizations that doesn't allow the contract to compile. Will address this in a future (more stable) release of the Sway compiler
